name: Deploy to Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install OpenSSH Client
        run: sudo apt-get install -y openssh-client

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACCjeD61RZyDUCrJjPxSPFWDOA7Nm5f8DpyJJh2SOGnKXwAAAKDTV9uQ01fb
            kAAAAAtzc2gtZWQyNTUxOQAAACCjeD61RZyDUCrJjPxSPFWDOA7Nm5f8DpyJJh2SOGnKXw
            AAAEDFFZWxCeotRB5tqlQyyQQZ8Tla80ytDj6zcoZkix9TMKN4PrVFnINQKsmM/FI8VYM4
            Ds2bl/wOnIkmHZI4acpfAAAAF2JpdG5hbWlAaXAtMTcyLTI2LTUtMTUzAQIDBAUG
            -----END OPENSSH PRIVATE KEY-----

      - name: Deploy to Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no bitnami@34.230.77.184 << 'EOF'
            cd /opt/bitnami/apache2/htdocs/Gerenciador_de_Bibliotecas
            git reset --hard HEAD
            git pull origin master
            # Adicione outros comandos de deploy conforme necessário
          EOF
